<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>click the circles. to the beat.</Description>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <Title>osu! (ruleset)</Title>
    <PackageId>ppy.osu.Game.Rulesets.Osu</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game\osu.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Mods\call_calling.mp3">
      <LogicalName>call_calling.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\call_calling.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\telegram-zvonok-pk.mp3">
      <LogicalName>telegram-zvonok-pk.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\telegram-zvonok-pk.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\steam-.mp3">
      <LogicalName>steam-.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\steam-.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\stuk-v-dver_BGgu9hKn.mp3">
      <LogicalName>stuk-v-dver_BGgu9hKn.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\stuk-v-dver_BGgu9hKn.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\1.mp3">
      <LogicalName>1.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\1.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\2.mp3">
      <LogicalName>2.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\2.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Mods\3.mp3">
      <LogicalName>3.mp3</LogicalName>
    </EmbeddedResource>
    <None Include="Mods\3.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
